language: ruby

branches:
  only:
    - "main"

services:
  - docker
    
before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker pull "$DOCKER_USERNAME/howezt-memoria:latest" || true
  - docker build -t $image --cache-from "$DOCKER_USERNAME/howezt-memoria:latest"
  - docker push "$DOCKER_USERNAME/howezt-memoria:latest"
  
install:
  - echo "ok"

